# ClangFormat
# Author: Eliot Hall
# This program formats all cpp files in the repository
name: ClangFormat

on:
  pull_request:
    branches: ["master"] 
  push:
    branches: ["master"]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Format .cpp and .hpp files
        run:
          clang-format ${{github.workspace}}/src/*.cpp ${{github.workspace}}/include/botui/*.hpp -style=file:${{github.workspace}}/.clang-format -i
      - name: Push to GitHub
        run: |
          git commit 
          git push origin