# ClangFormat
# Author: Eliot Hall
# This program formats all cpp files in the repository
name: ClangFormat

on:
  pull_request:
    branches: ["master"]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set Format Status
        uses: myrotvorets/set-commit-status-action@1.1.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowForks: true
          status: pending
          description: awaiting formatting
          context: format-status

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Format .cpp and .hpp files
        run:
          # don't include .c* since that would format .clang-format
          clang-format -style=file:${{github.workspace}}/.clang-format -i 
            $(find ${{github.workspace}} -name "*.h*") 
            $(find ${{github.workspace}} -name "*.c") 
            $(find ${{github.workspace}} -name "*.cpp")
      - name: Setup git config
        run: |
          git config user.name "Clang Formatter Bot"
          git config user.email ""
      - name: Push to GitHub  
        run:  |
          git add -A
          git diff --quiet HEAD || git commit -m "AutoFormat with clang-format" 
          git push origin HEAD:${{github.head_ref}}
          
      - name: Update Format Status
        uses: myrotvorets/set-commit-status-action@1.1.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowForks: true
          status: success
          description: All files formatted!
          context: format-status