# ClangFormat
# Author: Eliot Hall
# This program formats all cpp files in the repository
name: ClangFormat
on:
    push:
        branches:
            - master
jobs:
    format:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            
            - run:
                clang-format ${{github.workspace}}/src/*.cpp ${{github.workspace}}/include/*.hpp -style=file:${{github.workspace}}/.clang-format -i